services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.extra
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ./backend:/app/backend
      - ./src:/app/src
      - open-webui:/app/backend/data
      # where your huggingface model download
      # you need to insure model folder name followed this format: models--<provider>--<name>
      # e.g models--Qwen--Qwen3-0.6B
      - ${MODELS_DIR:-${HOME}/.cache/huggingface/hub}:/root/.cache/huggingface/hub
      - ${DOCKER_HOST:-/var/run/docker.sock}:/var/run/docker.sock
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      - GLOBAL_LOG_LEVEL=DEBUG
      - ENABLE_API_KEYS=true
      - USE_OLLAMA=false
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui:
    external: true
